---
# Deployment of our jenkins-service
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins-service
  namespace: keptn
spec:
  selector:
    matchLabels:
      run: jenkins-service
  replicas: 1
  template:
    metadata:
      labels:
        run: jenkins-service
    spec:
      containers:
        - name: jenkins-service
          image: grabnerandi/jenkins-service:0.1.0
          # image: keptnsandbox/jenkins-service:latest # Todo: Replace this with your image name
          ports:
            - containerPort: 8080
          env:
            - name: EVENTBROKER
              value: 'http://event-broker.keptn.svc.cluster.local/keptn'
            - name: CONFIGURATION_SERVICE
              value: 'http://configuration-service.keptn.svc.cluster.local:8080'
            - name: JENKINS_URL
              value: 'https://yourjenkinsserver.domain'
            - name: JENKINS_USER
              value: YOURJENKINS_USER
            - name: JENKINS_PASSWORD
              value: YOURJENKINS_PWD
            - name: KEPTN_ENDPOINT
              value: 'http://api.keptn.svc.cluster.local'
            - name: KEPTN_DOMAIN
              valueFrom:
                configMapKeyRef:
                  name: keptn-domain
                  key: app_domain
            - name: KEPTN_API_TOKEN
              valueFrom:
                secretKeyRef:
                  name: keptn-api-token
                  key: keptn-api-token
            - name: DT_API_TOKEN
              valueFrom:
                secretKeyRef:
                  name: dynatrace
                  key: DT_API_TOKEN
            - name: DT_TENANT
              valueFrom:
                secretKeyRef:
                  name: dynatrace
                  key: DT_TENANT              

---
# Expose jenkins-service via Port 8080 within the cluster
apiVersion: v1
kind: Service
metadata:
  name: jenkins-service
  namespace: keptn
  labels:
    run: jenkins-service
spec:
  ports:
    - port: 8080
      protocol: TCP
  selector:
    run: jenkins-service
---
## Subscribe to events via a keptn/distributor
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins-service-distributor
  namespace: keptn
spec:
  selector:
    matchLabels:
      run: distributor
  replicas: 1
  template:
    metadata:
      labels:
        run: distributor
    spec:
      containers:
        - name: distributor
          image: keptn/distributor:0.6.1
          ports:
            - containerPort: 8080
          resources:
            requests:
              memory: "32Mi"
              cpu: "50m"
            limits:
              memory: "128Mi"
              cpu: "500m"
          env:
            - name: PUBSUB_URL
              value: 'nats://keptn-nats-cluster'
            # listen to all events in sh.keptn. - see https://github.com/keptn/spec/blob/0.1.3/cloudevents.md
            - name: PUBSUB_TOPIC
              value: 'sh.keptn.>'
            - name: PUBSUB_RECIPIENT
              value: 'jenkins-service'
